### ISSUE TITLE
migrate to guppy 3.6.0 for basecalling

### ISSUE THREAD

**Issue by kapsakcj** [kapsakcj/nanoporeWorkflow#16]
This will be worth it, due to the accuracy increase in the high accuracy model.

New module name: `guppy/3.6.0-gpu`

More info: https://community.nanoporetech.com/posts/guppy-v3-6-0-release

**Comment by kapsakcj** [comment]
Seems that Guppy barcode trimming is still broken, and won't be implemented until the next release. See the nanopore community link above ^

"Hi Johannes Debler -- we had already started shipping this release when you put in your first post so the barcoding fix didn't make it in. It will come in the next release though. =)" -from Forrest Brennan

**Comment by johannes** [comment]
No idea what this is about, but I hope your problem will be fixed soon. (Seems you removed the highlight of my name after GitHub's mail wnet out :-D)

**Comment by kapsakcj** [comment]
Sorry about that! I was copying text from another location and accidentally tagged you.
